[tool]
[tool.poetry]
authors = ["hereinthejungle <<>>"]
description = ""
name = "repl_python3_telegram-np-news"
version = "0.1.0"
[tool.poetry.dependencies]
facebook-scraper = "*"
flask = "*"
python = "^3.8"
python-dotenv = "*"
python-telegram-bot = "*"
